# 版本号
version: '3'

# 定义服务
services:
  mysql57:
    build:
      context: ./mysql57
    image: mysql:5.7
    volumes:
      - ./mysql57/custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=measurement
